spring:
  application:
    name: series
  datasource:
    url: jdbc:h2:file:./data/testbd;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: user
    password: user
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true